RussianKdmidInstruction: &RussianKdmidInstruction
  Instruction: Take the link you received in your email after registering your request on the kdmid.ru website. Put the link instead of <link> in the command above. Send it to the chat (without apostrophes).

RussianKdmidServices: &RussianKdmidServices
  - Id: "0"
    Name: Check slots now
    <<: *RussianKdmidInstruction
  - Id: "1"
    Name: Slots auto notification
    <<: *RussianKdmidInstruction
  - Id: "2"
    Name: Slot auto booking
    Description: Auto slot booking
    Children:
      - Id: "0"
        Name: Book first slot
        <<: *RussianKdmidInstruction
      - Id: "1"
        Name: Book last slot
        <<: *RussianKdmidInstruction
      - Id: "2"
        Name: Book first slot in period
        Instruction: Take the link you received in your email after registering your request on the kdmid.ru website. Put the link instead of <link> in the command above. Change the start and end of the time periods in the command. Send it to the chat (without apostrophes).

RussianServices: &RussianServices
  - Id: RUS
    Name: Russian embassy
    Description: Choose the service of the Russian embassy
    Children:
      - Id: "0"
        Name: Passport
        Description: Passport services
        Children:
          - Id: "0"
            Name: International passport
            Description: International passport options
            Children:
              <<: *RussianKdmidServices
          - Id: "1"
            Name: Passport status
            <<: *RussianKdmidInstruction
      - Id: "1"
        Name: Notary
        Description: Notary services
        Children:
          - Id: "0"
            Name: Power of attorney
            Description: Power of attorney options
            Children:
              <<: *RussianKdmidServices
      - Id: "2"
        Name: Citizenship
        Description: Citizenship services
        Children:
          - Id: "0"
            Name: Citizenship renunciation
            Description: Renunciation options
            Children:
              <<: *RussianKdmidServices

ItalianPrenotamiInstruction: &ItalianPrenotamiInstruction
  Instruction: To do this I need your login and password from the prenotami website. You can get them by registering on the prenotami website. After that, you will receive a letter with a link to the prenotami website. Open this link and log in to your account. After that, put your login and password instead of <login;password> in the command above. Send it to the chat (without apostrophes).

ItalianPrenotamiServices: &ItalianPrenotamiServices
  - Id: "0"
    Name: Check slots now
    <<: *ItalianPrenotamiInstruction
  - Id: "1"
    Name: Slots auto notification
    <<: *ItalianPrenotamiInstruction

ItalianServices: &ItalianServices
  - Id: ITA
    Name: Italian embassy
    Description: Choose the service of the Italian embassy
    Children:
      - Id: "0"
        Name: Visa
        Description: Visa services
        Children:
          - Id: "0"
            Name: Tourism 1
            Description: Appointments visas for TOURISM (counter_1)
            Children:
              <<: *ItalianPrenotamiServices
          - Id: "1"
            Name: Tourism 2
            Description: Appointments visas for TOURISM (counter_2)
            Children:
              <<: *ItalianPrenotamiServices

Services:
  Id: SRV
  Name: Services
  Description: Choose the service you need
  Children:
    <<: *RussianServices
    <<: *ItalianServices
