RussianKdmidServices: &RussianKdmidServices
  - Id: "0"
    Name: Manual check slots
  - Id: "1"
    Name: Slots auto notification
  - Id: "2"
    Name: Auto booking first slot
  - Id: "3"
    Name: Auto booking first slot in period
  - Id: "4"
    Name: Auto booking last slot

RussianServices: &RussianServices
  Id: RUS
  Name: Russian embassy
  Description: Choose the service of the Russian embassy
  Children:    
    - Id: "0"
      Name: Passport
      Description: Passport services
      Children:
        - Id: "0"
          Name: Passport status
        - Id: "1"
          Name: Passport for 5 years
          Description: Application for a passport valid for 5 years
          Children:
            <<: *RussianKdmidServices
        - Id: "2"
          Name: Biometric passport
          Description: Application for biometric passport for 10 years
          Children:
            <<: *RussianKdmidServices
        - Id: "3"
          Name: Passport issuance
          Description: Issuance of ready passport (5 or 10 years)
          Children:
            <<: *RussianKdmidServices    
    - Id: "1"
      Name: Notary
      Description: Notary services
      Children:
        - Id: "0"
          Name: Marriage certificate in Serbia
          Description: Certificate for marriage in Serbia
          Children:
            <<: *RussianKdmidServices
        - Id: "1"
          Name: Marriage certificate
          Description: Marriage certificate verification
          Children:
            <<: *RussianKdmidServices
        - Id: "2"
          Name: Divorce certificate
          Description: Divorce documentation
          Children:
            <<: *RussianKdmidServices
        - Id: "3"
          Name: Name change
          Description: Documentation for name change
          Children:
            <<: *RussianKdmidServices        
        - Id: "4"
          Name: Electronic document verification
          Description: Verification of electronic documents
          Children:
            <<: *RussianKdmidServices
        - Id: "5"
          Name: Registration removal
          Description: Removal from registration records
          Children:
            <<: *RussianKdmidServices
        - Id: "6"
          Name: Consular registration
          Description: Application for consular registration
          Children:
            <<: *RussianKdmidServices
        - Id: "7"
          Name: Marriage registration
          Description: Application for marriage registration
          Children:
            <<: *RussianKdmidServices
        - Id: "8"
          Name: Will certification
          Description: Will certification services
          Children:
            <<: *RussianKdmidServices        
        - Id: "9"
          Name: Document claim
          Description: Document claim services
          Children:
            <<: *RussianKdmidServices
        - Id: "10"
          Name: Power of attorney certification
          Description: Certification of power of attorney
          Children:
            <<: *RussianKdmidServices
        - Id: "11"
          Name: Copy certification
          Description: Certification of document copies
          Children:
            <<: *RussianKdmidServices
        - Id: "12"
          Name: Translation certification
          Description: Certification of translations
          Children:
            <<: *RussianKdmidServices
        - Id: "13"
          Name: Consent certification
          Description: Certification of consent documents
          Children:
            <<: *RussianKdmidServices
        - Id: "14"
          Name: Certificate issuance
          Description: Issuance of certificates
          Children:
            <<: *RussianKdmidServices    
    - Id: "2"
      Name: Citizenship
      Description: Citizenship services
      Children:
        - Id: "0"
          Name: Child citizenship (both parents RF)
          Description: Citizenship for child with both parents Russian citizens
          Children:
            <<: *RussianKdmidServices
        - Id: "1"
          Name: Child citizenship (mixed marriage)
          Description: Citizenship for child with one Russian parent
          Children:
            <<: *RussianKdmidServices
        - Id: "2"
          Name: Citizenship termination
          Description: Application for termination of citizenship
          Children:
            <<: *RussianKdmidServices
        - Id: "3"
          Name: Citizenship verification
          Description: Verification of Russian citizenship
          Children:
            <<: *RussianKdmidServices
    - Id: "3"
      Name: Pension
      Description: Pension services
      Children:
        - Id: "0"
          Name: Initial pension consultation
          Description: Initial consultation on pension matters
          Children:
            <<: *RussianKdmidServices
        - Id: "1"
          Name: Other pension matters
          Description: Consultation on other pension matters
          Children:
            <<: *RussianKdmidServices
        - Id: "2"
          Name: Pension fund certificate
          Description: Certificate for Russian Pension Fund
          Children:
            <<: *RussianKdmidServices

ItalianPrenotamiServices: &ItalianPrenotamiServices
  - Id: "0"
    Name: Manual check slots
  - Id: "1"
    Name: Slots auto notification

ItalianServices: &ItalianServices
  Id: ITA
  Name: Italian embassy
  Description: Choose the service of the Italian embassy
  Children:
    - Id: "0"
      Name: Visa
      Description: Visa services
      Children:
        - Id: "0"
          Name: Tourism 1
          Description: Appointments visas for TOURISM (counter_1)
          Children:
            <<: *ItalianPrenotamiServices
        - Id: "1"
          Name: Tourism 2
          Description: Appointments visas for TOURISM (counter_2)
          Children:
            <<: *ItalianPrenotamiServices

Services:
  Id: SRV
  Name: Services
  Description: Choose the service you need
  Children:
    - <<: *RussianServices
    - <<: *ItalianServices
