# @format

Logging:
  LogLevel:
    Default: Information

Worker:
  Name: Scheduler
  Steps:
    - Name: Serbia
      Parallel: true
      Steps:
        - Name: Belgrade
          Steps:
            - Name: RussianEmbassy
              Parallel: true
              Recursively: true
              Duration: 00:00:10
              Steps:
                - Name: GetAvailableDates
                  Duration: 00:00:05
                - Name: NotifyUsers
                  Schedule:
                    IsEnabled: true
                    Delay: 00:00:05
              Schedule:
                IsEnabled: true
                Limit: 2
                Workdays: mon,tue,wed,thu,fri,sat,sun
          Schedule:
            IsEnabled: true
            Workdays: mon,tue,wed,thu,fri,sat,sun
    - Name: Hungary
      Parallel: true
      Steps:
        - Name: Budapest
          Steps:
            - Name: RussianEmbassy
              Parallel: true
              Recursively: true
              Duration: 00:00:10
              Steps:
                - Name: GetAvailableDates
                - Name: NotifyUsers
                  Schedule:
                    IsEnabled: true
                    Delay: 00:00:02
              Schedule:
                IsEnabled: true
                Limit: 5
                WorkDays: mon,tue,wed,thu,fri,sat,sun
          Schedule:
            IsEnabled: true
            Workdays: mon,tue,wed,thu,fri,sat,sun
