# @format

Logging:
  LogLevel:
    Default: Information

Worker:
  Name: Scheduler
  Steps:
    - Name: Serbia
      Parallel: true
      Steps:
        - Name: Belgrade
          Steps:
            - Name: Russian
              Parallel: true
              Recursively: true
              Steps:
                - Name: Look for appointments
                  Duration: 00:03:00
                - Name: Notify users
                  Schedule:
                    IsEnabled: true
                    Delay: 00:00:05
              Schedule:
                IsEnabled: true
                Limit: 5
                Workdays: mon,tue,wed,thu,fri,sat,sun
          Schedule:
            IsEnabled: true
            Workdays: mon,tue,wed,thu,fri,sat,sun