# @format

name: Deploy

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Git repository
        run: |
          cd /usr/src/embassy-access/
          git stash
          git pull origin main --recurse-submodules

      - name: Fast deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            chmod +x /usr/src/embassy-access/.github/workflows/deploy.sh
            /usr/src/embassy-access/.github/workflows/deploy.sh
