# @format

name: Deploy

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fast deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_KDMID_HOST }}
          username: ${{ secrets.DO_KDMID_USERNAME }}
          key: ${{ secrets.DO_KDMID_SSH }}
          passphrase: ${{ secrets.DO_KDMID_PASSPHRASE }}
          script: |
            chmod +x /app/src/embassy-access/.github/workflows/deploy.sh
            /app/src/embassy-access/.github/workflows/deploy.sh